const goods = [
  {
    img: "img/cards/card-1.jpg",
    name: "кремово-розовое",
    price: "1500",
    description: "с ароматом леденца",
    category: "soap",
    id: "0001",
    event: "regular",
  },
  {
    img: "img/cards/card-2.jpg",
    name: "кремово-зеленое",
    price: "1250",
    description: "с ароматом сухих роз",
    category: "soap",
    id: "0002",
    event: "regular",
  },
  {
    img: "img/cards/card-3.jpg",
    name: "маковое",
    price: "1450",
    description: "с ароматом маковых зерен",
    category: "soap",
    id: "0003",
    event: "regular",
  },
  {
    img: "img/cards/card-4.jpg",
    name: "мечты принцессы",
    price: "1900",
    description: "с ароматом единорога",
    category: "soap",
    id: "0004",
    event: "newYear",
  },
  {
    img: "img/cards/card-5.jpg",
    name: "мраморный кусок",
    price: "2900",
    description: "с ароматом сандаля",
    category: "soap",
    id: "0005",
    event: "regular",
  },
  {
    img: "img/cards/card-6.jpg",
    name: "пора в школу",
    price: "900",
    description: "с ароматом печальки",
    category: "soap",
    id: "0006",
    event: "regular",
  },
  {
    img: "img/cards/card-7.jpg",
    name: "нежный могильщик",
    price: "1199",
    description: "не путать с губкой для посуды",
    category: "soap",
    id: "0007",
    event: "regular",
  },
  {
    img: "img/cards/card-8.jpg",
    name: "Valentine's vibes",
    price: "1929",
    description: "с надеждой",
    category: "soap",
    id: "0008",
    event: "valentinesDay",
  },
];